apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  # These are example settings of domain.
  # example.org will be used for routes having app=prod.
  # example.org: ""
  #   selector:
  #     app: prod
  # Default value for domain, for routes that does not have app=prod labels.
  # Although it will match all routes, it is the least-specific rule so it
  # will only be used if no other domain matches.
  {{ .Values.domain }}: ""
---
apiVersion: v1
kind: ConfigMap
data:
  istio.sidecar.includeOutboundIPRanges: '{{ join "," .Values.outboundIPRanges }}'
metadata:
  name: config-network
  namespace: knative-serving
