apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: baseimages.resources.dispatchframework.io
spec:
  group: resources.dispatchframework.io
  version: v1
  names:
    kind: BaseImage
    plural: baseimages
  scope: Namespaced