# Default values for image-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  pullPolicy: IfNotPresent
  # NOTE: replace with your client id & secret with helm install
  skipAuth: false
  organization: dispatch
  #host_ip:
  #host: dispatch.vmware.com
  port: 443
  debug: true
  image:
    tag: v0.1.13
    host: vmware
  data:
    persist: false
  db:
    backend: postgres
    host: postgresql
    port: 5432
    user: vmware
    password: dispatch
    database: dispatch
    namespace: dispatch
    release: postgres
  ingress:
    enabled: true
    # Used to create Ingress record (should used with service.type: ClusterIP).
    # host: dispatch.vmware.com
    # The annotationsPrefix that your ingress controller requires. default - nginx.ingress.kubernetes.io for
    # nginx ingress controllers.
    annotationsPrefix: nginx.ingress.kubernetes.io
    annotations:
      # Specify any additional ingress annotations here. These will be applied to all ingress resources.
      # kubernetes.io/ingress.class: "nginx"
  registry:
    insecure: false
    uri: docker-docker-registry.docker.svc.cluster.local:5000
  rabbitmq:
    username: dispatch
    password: dispatch
    port: 5672
  kafka:
    brokers:
    - transport-kafka.dispatch:9092
  tls:
    secretName: dispatch-tls
  tracer:
    endpoint:
  rbac:
    create: true
    # Ignored, if rbac.create is true
    serviceAccountName: default
  resources:
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    #requests:
    #  cpu: 100m
    #  memory: 128Mi
