# Default values for image-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  pullPolicy: IfNotPresent
  organization: dispatch
  image:
    tag: v0.1.1
    host: vmware
  debug: true
  trace: false
  data:
    persist: false
  host: dispatch.vmware.com
  port: 443
  tls:
    secretName: dispatch-tls
rabbitmq:
  rabbitmqPassword: serverless
