apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "fullname" . }}-service-account
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Values.global.tag .Values.image.tag }}"
          imagePullPolicy: {{ default .Values.global.pullPolicy .Values.image.pullPolicy }}
          args:
            - "--host=0.0.0.0"
            - "--port={{ .Values.service.internalPort }}"
            - "--tls-port=443"
            - "--tls-certificate=/data/tls/tls.crt"
            - "--tls-key=/data/tls/tls.key"
            - "--namespace={{ .Release.Namespace }}"
            {{- if .Values.global.debug }}
            - "--debug"
            - "--trace"
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          volumeMounts:
            - mountPath: "/data/{{ template "name" . }}"
              name: {{ template "fullname" . }}
            - mountPath: "/var/run/docker.sock"
              name: {{ template "fullname" . }}-docker
            - mountPath: "/data/tls"
              name: tls
              readOnly: true
          env:
            - name: DOCKER_API_VERSION
              value: "1.23"
            - name: ORGANIZATION
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: organization
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: {{ template "fullname" . }}
{{- if default .Values.global.data.persist .Values.data.persist }}
          hostPath:
            path: {{ .Values.data.hostPath }}
{{- else }}
          emptyDir: {}
{{- end }}
        - name: {{ template "fullname" . }}-docker
          hostPath:
            path: /var/run/docker.sock
        - name: tls
          secret:
            secretName: serverless-vmware-tls
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
