# A cluster role for create/get/list/delete/update secrets
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "fullname" . }}-cluster-role
rules:
- apiGroups: ["projectriff.io"]
  resources: ["functions", "topics"]
  verbs: ["create", "delete"]
