apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ if .Values.global.rbac.create }}{{ template "fullname" . }}-service-account{{ else }}"{{ .Values.global.rbac.serviceAccountName }}"{{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ default .Values.global.image.host .Values.image.host }}/{{ default .Values.global.image.repository .Values.image.repository }}:{{ default .Values.global.image.tag .Values.image.tag }}"
          imagePullPolicy: {{ default .Values.global.pullPolicy .Values.image.pullPolicy }}
          args:
            - "function-manager"
            - "--config=/data/config/config.yaml"
            - "--host=0.0.0.0"
            - "--port={{ .Values.service.internalPort }}"
            - "--db-file={{ default .Release.Name .Values.global.db.release }}-{{ .Values.global.db.host }}.{{ default .Release.Namespace .Values.global.db.namespace }}:{{ .Values.global.db.port }}"
            - "--db-backend={{ .Values.global.db.backend }}"
            - "--db-username={{ .Values.global.db.user }}"
            - "--db-password={{ .Values.global.db.password }}"
            - "--db-database={{ .Values.global.db.database }}"
            - "--image-manager={{ .Release.Name }}-image-manager"
            - "--service-manager={{ .Release.Name }}-service-manager"
            - "--secret-store={{ .Release.Name }}-secret-store"
            - "--tracer={{ .Values.global.tracer.endpoint }}"
            {{- if .Values.global.debug }}
            - "--debug"
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.internalPort }}
              httpHeaders:
              - name: Cookie
                value: cookie
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.internalPort }}
              httpHeaders:
              - name: Cookie
                value: cookie
            initialDelaySeconds: 10
            periodSeconds: 3
          volumeMounts:
            - mountPath: /data/config
              name: config
              readOnly: true
          env:
            - name: DOCKER_API_VERSION
              value: "1.24"
            - name: DOCKER_HOST
              value: "tcp://localhost:2375"
          resources:
{{ .Values.resources | default .Values.global.resources | toYaml | indent 12 }}
        - name: {{ .Chart.Name }}-docker
          image: docker:dind
          imagePullPolicy: {{ default .Values.global.pullPolicy .Values.image.pullPolicy }}
          {{- if default .Values.global.registry.insecure .Values.registry.insecure }}
          args:
          - --insecure-registry={{ default .Values.global.registry.uri .Values.registry.uri }}
          {{- end }}
          securityContext:
            privileged: true
          volumeMounts:
          - name: docker-graph-storage
            mountPath: /var/lib/docker
          resources:
{{ .Values.dindResources | default .Values.global.resources | toYaml | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: config.yaml
              path: config.yaml
        - name: docker-graph-storage
          emptyDir: {}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
