apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  # name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.http.externalPort }}
    targetPort: {{ .Values.service.http.internalPort }}
    protocol: TCP
    name: http
  - port: {{ .Values.service.https.externalPort }}
    targetPort: {{ .Values.service.https.internalPort }}
    protocol: TCP
    name: https
  selector:
    app: {{ template "name" . }}
    # app: {{ template "fullname" . }}
