apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.kongName }}
spec:
  replicas: {{ .Values.kongInstanceReplicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.kongMaxSurge }}
      maxUnavailable: {{ .Values.kongMaxUnavailable }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-{{ .Values.kongName }}
        app:  {{ .Release.Name }}-{{ .Values.kongName }}
    spec:
      containers:
      - name: kong
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: KONG_NGINX_DAEMON
            value: 'off'
          - name: KONG_DATABASE
            value: {{ .Values.database }}
          - name: KONG_LOG_LEVEL
            value: {{ .Values.logLevel }}
          - name: KONG_HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: KONG_PG_DATABASE
            value: {{ .Values.postgresql.postgresDatabase }}
          - name: KONG_PG_USER
            value: {{ .Values.postgresql.postgresUser }}
          - name: KONG_PG_PASSWORD
            value: {{ .Values.postgresql.postgresPassword }}
          - name: KONG_PG_HOST
            value: "{{ default .Release.Name .Values.postgresql.postgresRelease }}-{{ .Values.postgresql.postgresHost }}.{{ default .Release.Namespace .Values.postgresql.postgresNamespace }}"
          - name: KONG_PG_PORT
            value: {{ .Values.postgresql.postgresPort | quote }}
        command: [ "/bin/sh", "-c", "KONG_CLUSTER_ADVERTISE=$(KONG_HOST_IP):7946 kong start --conf /data/kong/kong.conf --nginx-conf /data/nginx/nginx.conf --run-migrations --vv" ]
        ports:
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: surf-tcp
          containerPort: 7946
          protocol: TCP
        - name: surf-udp
          containerPort: 7946
          protocol: UDP
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 3
        volumeMounts:
          - name: kong-conf
            mountPath: /data/kong
          - name: nginx-conf
            mountPath: /data/nginx
          - name: api-server-tls
            mountPath: /usr/local/kong/tls
            readOnly: true
          - name: serverless-transform-plugin-volume
            mountPath: /usr/local/kong/custom/kong/plugins/serverless-transformer
      volumes:
        - name: kong-conf
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: kong-conf
              path: kong.conf
        - name: nginx-conf
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: nginx-conf
              path: nginx.conf
        - name: api-server-tls
          secret:
            secretName: api-dispatch-tls
        - name: serverless-transform-plugin-volume
          configMap:
            name: {{ template "fullname" . }}-plugin
