{{- $ingress_host := default .Values.global.host .Values.ingress.host -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ default .Values.global.image.host .Values.image.host }}/{{ .Values.image.repository }}:{{ default .Values.global.image.tag .Values.image.tag }}"
          imagePullPolicy: {{ default .Values.global.pullPolicy .Values.image.pullPolicy }}
          args:
            - "--cookie-name=_oauth2_proxy"
            - "--host=0.0.0.0"
            - "--port={{ .Values.service.internalPort }}"
            - "--db-file={{ default .Release.Name .Values.global.db.release }}-{{ .Values.global.db.host }}.{{ default .Release.Namespace .Values.global.db.namespace }}:{{ .Values.global.db.port }}"
            - "--db-backend={{ .Values.global.db.backend }}"
            - "--db-username={{ .Values.global.db.user }}"
            - "--db-password={{ .Values.global.db.password }}"
            - "--db-database={{ .Values.global.db.database }}"
            - "--tls-port=443"
            - "--tls-certificate=/data/tls/tls.crt"
            - "--tls-key=/data/tls/tls.key"
            - "--oauth2-proxy-auth-url=http://localhost:{{ .Values.oauth2proxy.service.internalPort }}/v1/iam/oauth2/auth"
            {{- if .Values.enableBootstrapMode }}
            - "--enable-bootstrap-mode"
            {{- end }}
            {{- if .Values.global.skipAuth }}
            - "--skip-auth"
            {{- end }}
            {{- if .Values.global.debug }}
            - "--debug"
            {{- end }}
            {{- if .Values.global.trace }}
            - "--trace"
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          volumeMounts:
            - mountPath: "/data/tls"
              name: tls
              readOnly: true
          env:
            - name: ORGANIZATION
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: organization
            {{- if .Values.enableBootstrapMode }}
            - name: IAM_BOOTSTRAP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: bootstrap_user
            - name: IAM_BOOTSTRAP_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: bootstrap_public_key
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.internalPort }}
              httpHeaders:
              - name: Cookie
                value: cookie
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.internalPort }}
              httpHeaders:
              - name: Cookie
                value: cookie
            initialDelaySeconds: 10
            periodSeconds: 3
          resources:
{{ toYaml .Values.resources | default .Values.global.resources | indent 12 }}
        - name: oauth2-proxy
          image: {{ .Values.oauth2proxy.image }}
          imagePullPolicy: {{ default .Values.global.pullPolicy .Values.image.pullPolicy }}
          args:
            - "-provider={{ .Values.oauth2proxy.provider }}"
            {{- if eq .Values.oauth2proxy.provider "oidc" }}
            - "-oidc-issuer-url={{ .Values.oauth2proxy.oidcIssuerURL }}"
            {{- end }}
            - "-http-address=0.0.0.0:{{ .Values.oauth2proxy.service.internalPort }}"
            {{- if .Values.oauth2proxy.redirectPath }}
              ## the OAuth Redirect URL.
              # defaults to the "https://" + requested host header + "/oauth2/callback"
              {{- if eq (.Values.global.port | toString) "443" }}
            - "-redirect-url=https://{{ default $ingress_host .Values.global.host_ip }}{{ .Values.oauth2proxy.redirectPath }}"
              {{- else }}
            - "-redirect-url=https://{{ default $ingress_host .Values.global.host_ip }}:{{ .Values.global.port }}{{ .Values.oauth2proxy.redirectPath }}"
              {{- end }}
            {{- end }}
            - "-set-xauthrequest"
            - "-email-domain=*"
            - "-proxy-prefix=/v1/iam/oauth2"
          livenessProbe:
            tcpSocket:
              port: {{ .Values.oauth2proxy.service.internalPort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.oauth2proxy.service.internalPort }}
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: client_id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: client_secret
            - name: OAUTH2_PROXY_COOKIE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: cookie_name
            - name: OAUTH2_PROXY_COOKIE_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: cookie_domain
            - name: OAUTH2_PROXY_COOKIE_EXPIRE
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: cookie_expire
            - name: OAUTH2_PROXY_COOKIE_REFRESH
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: cookie_refresh
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: cookie_secret
          ports:
            - containerPort: {{ .Values.oauth2proxy.service.internalPort }}
          resources:
{{ toYaml .Values.resources | default .Values.global.resources | indent 12 }}
      volumes:
        - name: {{ template "fullname" . }}
{{- if default .Values.global.data.persist .Values.data.persist }}
          hostPath:
            path: {{ .Values.data.hostPath }}
{{- else }}
          emptyDir: {}
{{- end }}
        - name: tls
          secret:
            secretName: dispatch-tls
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
