{{- if .Values.ingress.enabled -}}
{{- $tls := default .Values.global.tls .Values.ingress.tls -}}
{{- $ingress_host := default .Values.global.host .Values.ingress.host -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-noauth
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ .Values.global.ingress.annotationsPrefix }}/configuration-snippet: |
      error_page 403 = @403.json;
      error_page 401 = @401.json;
    {{ .Values.global.ingress.annotationsPrefix }}/server-snippet: |
      location @403.json {
        default_type application/json;
        return 403 '{"code": 403,"message": "Forbidden, please make sure you have required privileges"}';
      }
      location @401.json {
        default_type application/json;
        return 401 '{"code": 401,"message": "Unauthorized, please make sure you are logged in or provide a valid token"}';
      }
spec:
  rules:
    - http:
        paths:
          - path: /v1/iam/oauth2
            backend:
              serviceName: {{ include "fullname" . }}-oauth2-proxy
              servicePort: {{ .Values.oauth2proxy.service.externalPort }}
          - path: /v1/iam/redirect
            backend:
              serviceName: {{ include "fullname" . }}
              servicePort: {{ .Values.service.externalPort }}
          - path: /v1/version
            backend:
              serviceName: {{ include "fullname" . }}
              servicePort: {{ .Values.service.externalPort }}
      {{- if $ingress_host }}
      host: {{ $ingress_host }}
      {{- end -}}
  {{- if $tls.secretName }}
  tls:
    - secretName: {{ $tls.secretName }}
      {{- if $ingress_host }}
      hosts:
        - {{ default .Values.global.host .Values.ingress.host }}
      {{- end -}}
  {{- end -}}
{{- end -}}
