# Default values for image-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
maxUnavailable: 0
maxSurge: 1
image:
  repository: dispatch-image-manager
  # host: vmware
  # tag: latest
  # pullPolicy: Always
service:
  name: image-manager
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  enabled: true
  # Used to create Ingress record (should used with service.type: ClusterIP).
  # host: dispatch.vmware.com
  paths:
  - /v1/image
  - /v1/baseimage
  annotations:
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # secretName: dispatch-tls
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi
registry: {}
  # insecure: false
  # uri: docker-docker-registry.docker.svc.cluster.local:5000
data:
  # persist: false
  hostPath: /var/image-manager
